fix：CodeQL.yaml

diff --git a/.github/workflows/CodeQL.yaml b/.github/workflows/CodeQL.yaml
--- a/.github/workflows/CodeQL.yaml
+++ b/.github/workflows/CodeQL.yaml
@@ -34,10 +34,16 @@ jobs:
     - name: PR Title Verify
       uses: satvik-s/pr-title-check@1.2.1
       with:
-    # regex pattern to match against
-        pattern: ^\d{9} - work\d+$
-    # flags for the regex input
-        flags: i
+        pattern: '^\d{9} - work\d+$'
+      id: pr-title-check
+
+    - name: Check PR Title
+      run: |
+        if [ "${{ steps.pr-title-check.outputs.valid }}" == "false" ]; then
+        echo "Error: PR title does not match the required format."
+        exit 1
+        fi
+        continue-on-error: true
 
     - name: Initialize CodeQL
       uses: github/codeql-action/init@v2
